Game logic
DennisOsido/Tic-Tac-Toe pull request #4
Opened 2020-05-10 12:55 UTC by Buyaki01

- Worked on game_logic branch
- Added real logic to the tic tac toe game
- Created three more files: board.rb, players.rb and logic.rb in the lib folder
- board.rb is responsible for the display of the board
- players.rb is responsible for the display of the player's names
- logic.rb is responsible for the logic of the game i.e how to determine the winner and when it's a draw

2020-05-11 06:45 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @Buyaki01 @DennisOsido 

Nice introduction to this milestone.
There are some bugs to fix.

1. Error when starting the application
```ruby
$ ./bin/main.rb 
./bin/main.rb: line 6: require_relative: command not found
./bin/main.rb: line 7: require_relative: command not found
./bin/main.rb: line 8: require_relative: command not found
./bin/main.rb: line 10: @board: command not found
./bin/main.rb: line 11: @winner: command not found
./bin/main.rb: line 12: @turn: command not found
./bin/main.rb: line 14: syntax error near unexpected token `('
./bin/main.rb: line 14: `def take_turn(player, cell)'
```
But this is working
```ruby
$ ruby ./bin/main.rb 
0 |1 |2 
  |  |  
__|__|__
3 |4 |5 
  |  |  
__|__|__
6 |7 |8 
  |  |  
  |  | 
Player1 write your name
```

2. Take a look at this screenshot
![Screenshot from 2020-05-11 01-49-23](https://user-images.githubusercontent.com/8848104/81528005-b2260600-9329-11ea-9de0-1d6e317c4a70.png)
It's possible to enter **Empty name**. Please, I think you should assign a random name is such a case

Except for those issues, everything is OK. The game works well.

3. Your OOP implementation is not good except for the `Player` class.
You need to move some methods from the `bin/main.rb` file. Please, correctly remember the OOP principles before moving any function.

Kindly make the changes and submit a new code review request.
Thanks 
Mael FOSSO

2020-05-11 06:45 UTC, maelfosso commented on bin/main.rb
> +end
Move it in `Board`

2020-05-11 06:45 UTC, maelfosso commented on bin/main.rb
> +    end
Check the validity, move into `Board`

2020-05-11 06:45 UTC, maelfosso commented on bin/main.rb
> +    end
Switching the current player or indicate who is the current player, should come from `Board`

2020-05-11 06:45 UTC, maelfosso commented on bin/main.rb
> +            end
Improve your writing code.
It's similar to switching the player, move into `Board` class

2020-05-11 06:45 UTC, maelfosso commented on bin/main.rb
> +    @winner = @turn if check_win(@board.board) == true
Check the win should be done into `Board`

2020-05-16 01:38 UTC, rOluochKe requested changes
Hello Team
### Your branch has some merge conflict that you need to solve before requesting for another code review
![merge](https://user-images.githubusercontent.com/8114528/82107305-1c2a1b00-972f-11ea-91a1-b242f07d7c2b.png)

2020-05-17 17:47 UTC, pelzolga123 approved these changes
Approved.

2020-05-17 17:48 UTC, pelzolga123 commented
## Hi Team,
## Project looks good. Congratulation :+1: Approved.
Go ahead and merge to development.
_Goodluck in your next project_ *Happy coding*

2020-05-18 06:54 UTC, merged